name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

    - name: Deploy code to GCP VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          set -e

          echo "[1] Mark repo as safe"
          git config --global --add safe.directory /home/github-actions/DUD

          echo "[2] Set correct ownership"
          sudo chown -R github-actions:github-actions /home/github-actions/DUD

          echo "[3] Cleanup and install"
          cd /home/github-actions/DUD
          sudo rm -rf node_modules
          sudo rm -f package-lock.json
          npm install

          echo "[4] Build backend"
          npx tsc --project tsconfig.server.json

          echo "[5] Restart PM2"
          pm2 restart dud-backend || pm2 start dist/server/index.js --name dud-backend
        EOF
