name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

    - name: Deploy code to GCP VM
      run: |
        ssh -o StrictHostKeyChecking=no adityasdud@${{ secrets.GCP_VM_IP }} << 'EOF'
          # Increase memory for TypeScript compiler
          export NODE_OPTIONS="--max-old-space-size=2048"

          # Clone repo if not already present
          cd ~/DUD || (git clone https://github.com/adityasi3578/DUD.git && cd DUD)

          # Pull latest changes
          cd ~/DUD
          git pull origin main

          # Move to backend directory
          cd server

          # Install backend dependencies
          npm install

          # Compile TypeScript (output to dist/)
          npx tsc

          # Start or restart server using PM2
          pm2 restart dist/index.js || pm2 start dist/index.js --name dud-backend
        EOF
